python manage.py migrate rave 0003 --fake
python manage.py migrate rave 0004 --fake
python manage.py migrate rave 0005 --fake
python manage.py migrate rave 0006 --fake
python manage.py migrate rave 0007 --fake
python manage.py migrate rave 0008 --fake
python manage.py migrate rave 0009 --fake
python manage.py migrate rave 0010 --fake
python manage.py migrate rave 0011 --fake
python manage.py migrate rave 0012 --fake
python manage.py migrate rave 0013 --fake
python manage.py migrate rave 0014 --fake
python manage.py migrate rave 0015 --fake
python manage.py migrate rave 0016 --fake
python manage.py migrate rave 0017 --fake
python manage.py migrate rave 0018 --fake
python manage.py migrate rave 0019 --fake
python manage.py migrate rave 0020 --fake
python manage.py migrate rave 0021 --fake
python manage.py migrate rave 0022 --fake
python manage.py migrate rave 0023 --fake
python manage.py migrate rave 0024 --fake
python manage.py migrate rave 0025 --fake
python manage.py migrate rave 0026 --fake
python manage.py migrate rave 0027 --fake
python manage.py migrate rave 0028 --fake
python manage.py migrate rave 0029 --fake
python manage.py migrate rave 0030 --fake
python manage.py migrate rave 0031 --fake
python manage.py migrate rave 0032 --fake
python manage.py migrate rave 0033 --fake
python manage.py migrate rave 0034 --fake
python manage.py migrate rave 0035 --fake
python manage.py migrate rave 0036 --fake
python manage.py migrate rave 0037 --fake
python manage.py migrate rave 0038 --fake
python manage.py migrate rave 0039 --fake
python manage.py migrate rave 0040 --fake
python manage.py migrate rave 0041 --fake
python manage.py migrate rave 0042 --fake
python manage.py migrate rave 0043 --fake
python manage.py migrate rave 0044 --fake
python manage.py migrate rave 0045 --fake
python manage.py migrate rave 0046 --fake
python manage.py migrate rave 0047 --fake
python manage.py migrate rave 0048 --fake
python manage.py migrate rave 0049 --fake
python manage.py migrate rave 0050 --fake
python manage.py migrate rave 0051 --fake
python manage.py migrate rave 0052 --fake
python manage.py migrate rave 0053 --fake
python manage.py migrate rave 0054 --fake
python manage.py migrate rave 0055 --fake
python manage.py migrate rave 0056 --fake
python manage.py migrate rave 0057 --fake
python manage.py migrate rave 0058 --fake
python manage.py migrate rave 0059 --fake
