# Generated by Django 5.2.3 on 2025-06-25 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0002_alter_bookingsegment_add_dtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, choices=[('NEWS', 'News'), ('SPORTS', 'Sports'), ('ENTERTAINMENT', 'Entertainment'), ('DOCUMENTARY', 'Documentary'), ('MOVIE', 'Movie'), ('SERIES', 'Series'), ('DRAMA', 'Drama'), ('TALK SHOW', 'Talk Show')], max_length=50, null=True)),
                ('language', models.CharField(blank=True, choices=[('ENGLISH', 'English'), ('SWAHILI', 'Swahili'), ('FRENCH', 'French'), ('SPANISH', 'Spanish'), ('FRENCH', 'French'), ('ARABIC', 'Arabic'), ('MANDARIN', 'Mandarin'), ('HINDI', 'Hindi')], max_length=50, null=True)),
                ('audience', models.CharField(blank=True, choices=[('GENERAL', 'General'), ('CHILDREN', 'Children'), ('TEENS', 'Teens'), ('ADULTS', 'Adults'), ('SENIORS', 'Seniors')], max_length=50, null=True)),
                ('broadcast_days', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('producer', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('writer', models.CharField(blank=True, max_length=255, null=True)),
                ('presenter', models.CharField(blank=True, max_length=255, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('production_type', models.CharField(blank=True, choices=[('LIVE', 'Live'), ('RECORDED', 'Recorded'), ('ANIMATED', 'Animated'), ('DOCUMENTARY', 'Documentary'), ('SYNDICATED', 'Syndicated')], max_length=50, null=True)),
                ('production_company', models.CharField(blank=True, max_length=255, null=True)),
                ('production_location', models.CharField(blank=True, max_length=255, null=True)),
                ('broadcast_network', models.CharField(blank=True, max_length=255, null=True)),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('repeat_schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('parental_rating', models.CharField(blank=True, choices=[('G', 'General Audience'), ('PG', 'Parental Guidance'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], max_length=5, null=True)),
                ('covert_image', models.CharField(blank=True, max_length=255, null=True)),
                ('script_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 9, 56, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 9, 56, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 9, 56, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 9, 56, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 9, 56, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 9, 56, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 9, 56, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
