# Generated by Django 5.2.3 on 2025-06-30 07:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0006_rename_cast_tvprogram_prog_cast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breaklayout',
            name='description',
        ),
        migrations.RemoveField(
            model_name='breaklayout',
            name='name',
        ),
        migrations.AddField(
            model_name='breaklayout',
            name='tvprogram',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.tvprogram'),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 30, 7, 37, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 30, 7, 37, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 30, 7, 37, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 30, 7, 37, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 30, 7, 37, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 30, 7, 37, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 30, 7, 37, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
