# Generated by Django 5.2.3 on 2025-07-09 11:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0008_alter_bookingsegment_add_dtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 9, 11, 33, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 9, 11, 33, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 9, 11, 33, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 9, 11, 33, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 9, 11, 33, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 9, 11, 33, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 9, 11, 33, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='AdvertMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_file', models.CharField(blank=True, max_length=300, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('aspect_ratio', models.CharField(blank=True, help_text='Video aspect ratio, e.g., 16:9', max_length=20, null=True)),
                ('resolution', models.CharField(blank=True, help_text='Resolution of the video, e.g., 1920x1080', max_length=50, null=True)),
                ('rating', models.CharField(blank=True, choices=[('G', 'General Audience'), ('PG', 'Parental Guidance'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Client', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.client')),
            ],
        ),
    ]
