# Generated by Django 5.2.3 on 2025-11-17 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0017_orderbooking_order_alter_bookingsegment_add_dtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='report_runner_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='report_viewer_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 17, 8, 48, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 17, 8, 48, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 17, 8, 48, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 17, 8, 48, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 17, 8, 48, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 17, 8, 48, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 17, 8, 48, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
