# Generated by Django 5.2.3 on 2026-02-10 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0022_reasonvoidbooking_orderbooking_add_dtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbooking',
            name='void_dtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderbooking',
            name='void_login',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 10, 3, 8, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 10, 3, 8, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 10, 3, 8, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 10, 3, 8, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 10, 3, 8, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 10, 3, 8, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 10, 3, 8, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 10, 3, 8, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
