# Generated by Django 5.2.3 on 2026-02-18 12:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0024_breaklayoutline_title_alter_bookingsegment_add_dtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='break_layout_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.breaklayoutline'),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 18, 12, 39, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 18, 12, 39, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 18, 12, 39, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 18, 12, 39, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 18, 12, 39, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 18, 12, 39, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 18, 12, 39, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 18, 12, 39, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
