# Generated by Django 4.0.5 on 2022-06-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=200)),
                ('server_type', models.CharField(choices=[('DS', 'DB-SERVER'), ('AS', 'AUDIO-SERVER')], max_length=2)),
                ('server_ip', models.CharField(blank=True, max_length=24, null=True)),
                ('server_port', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=200)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.server')),
            ],
        ),
    ]
