# Generated by Django 4.0.5 on 2022-09-29 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AudioStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=200)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.cluster')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='cluster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.cluster'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StorageDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_name', models.CharField(max_length=100)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('audio_store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.audiostore')),
            ],
        ),
        migrations.CreateModel(
            name='StationSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_folder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.audiofolder')),
                ('audio_store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.audiostore')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.database')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.station')),
            ],
        ),
        migrations.AddField(
            model_name='audiostore',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.server'),
        ),
        migrations.AddField(
            model_name='audiostore',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.station'),
        ),
        migrations.AddField(
            model_name='audiofolder',
            name='disk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.storagedisk'),
        ),
    ]
