# Generated by Django 4.0.5 on 2022-09-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0002_audiofolder_audiostore_station_server_cluster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='server_port',
        ),
        migrations.AddField(
            model_name='database',
            name='db_port',
            field=models.IntegerField(default=0),
        ),
    ]
