# Generated by Django 4.0.5 on 2022-10-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0003_remove_server_server_port_database_db_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagedisk',
            name='audio_store',
        ),
        migrations.AddField(
            model_name='storagedisk',
            name='audio_server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.server'),
            preserve_default=False,
        ),
    ]
