# Generated by Django 4.0.5 on 2022-10-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0004_remove_storagedisk_audio_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('DBS', 'DB-SERVER'), ('ADS', 'AUDIO-SERVER')], max_length=3),
        ),
    ]
