# Generated by Django 4.0.5 on 2023-08-31 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0006_content_contentauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.station')),
            ],
        ),
    ]
