# Generated by Django 4.0.5 on 2023-09-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0007_useraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='port_no',
            field=models.IntegerField(default=5432),
        ),
        migrations.AddField(
            model_name='station',
            name='db_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
