# Generated by Django 4.0.5 on 2023-09-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0008_server_port_no_station_db_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='db_admin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='db_admin_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
