# Generated by Django 4.0.5 on 2023-09-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0009_server_db_admin_server_db_admin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('reset_password', models.IntegerField(default=0)),
            ],
        ),
    ]
