# Generated by Django 4.0.5 on 2024-06-01 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0010_userconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedisk',
            name='free',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='storagedisk',
            name='last_refresh',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 1, 18, 35), null=True),
        ),
        migrations.AddField(
            model_name='storagedisk',
            name='raw_disk_name',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
