# Generated by Django 4.0.5 on 2024-06-01 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0011_storagedisk_free_storagedisk_last_refresh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagedisk',
            old_name='free',
            new_name='free_space',
        ),
        migrations.AlterField(
            model_name='storagedisk',
            name='last_refresh',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 1, 19, 43), null=True),
        ),
    ]
