# Generated by Django 5.2.3 on 2025-11-09 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0012_rename_free_storagedisk_free_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='storagedisk',
            name='last_refresh',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 9, 8, 47, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
