# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-18 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=15)),
                ('add_login', models.CharField(max_length=15)),
                ('add_dtime', models.DateTimeField(default=datetime.datetime(2020, 4, 18, 10, 47))),
            ],
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 10, 47)),
        ),
        migrations.AddField(
            model_name='clientgroup',
            name='add_login',
            field=models.CharField(default=datetime.datetime(2020, 4, 18, 10, 47), max_length=25),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rave.Person')),
            ],
            bases=('rave.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Gender'),
        ),
    ]
