# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-18 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0002_auto_20200418_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='person_ptr',
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 11, 27)),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_login',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='SalesPerson',
        ),
    ]
