# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-18 11:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0003_auto_20200418_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=15)),
                ('add_login', models.CharField(max_length=15)),
                ('add_dtime', models.DateTimeField(default=datetime.datetime(2020, 4, 18, 11, 28))),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Gender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 11, 28)),
        ),
    ]
