# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-24 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0004_auto_20200418_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExlusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daypart1', models.CharField(max_length=96)),
                ('daypart2', models.CharField(max_length=96)),
                ('daypart3', models.CharField(max_length=96)),
                ('daypart4', models.CharField(max_length=96)),
                ('daypart5', models.CharField(max_length=96)),
                ('daypart6', models.CharField(max_length=96)),
                ('daypart7', models.CharField(max_length=96)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 18, 17)),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 18, 17)),
        ),
    ]
