# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-25 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0005_auto_20200424_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeExlusion',
            new_name='TypeExclusion',
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 12, 34)),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 12, 34)),
        ),
    ]
