# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-27 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0006_auto_20200425_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceExclusions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('detail_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 12, 7)),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 12, 7)),
        ),
    ]
