# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-27 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0007_auto_20200427_1207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoiceExclusions',
            new_name='VoiceExclusion',
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 17, 45)),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 17, 45)),
        ),
    ]
