# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-28 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0008_auto_20200427_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 28, 16, 57), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_login',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 28, 16, 57), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_login',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.Gender'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='typeexclusion',
            name='daypart1',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='typeexclusion',
            name='daypart2',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='typeexclusion',
            name='daypart3',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='typeexclusion',
            name='daypart4',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='typeexclusion',
            name='daypart5',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='typeexclusion',
            name='daypart6',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='typeexclusion',
            name='daypart7',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='typeexclusion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
