# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-30 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0009_auto_20200428_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceOver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('add_login', models.CharField(blank=True, max_length=15, null=True)),
                ('add_dtime', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 30, 18, 18), null=True)),
                ('daypart1', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart2', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart3', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart4', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart5', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart6', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart7', models.CharField(blank=True, max_length=96, null=True)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.Gender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 30, 18, 18), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 30, 18, 18), null=True),
        ),
    ]
