# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-06-01 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0011_auto_20200523_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bill_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_no', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('client_email', models.CharField(blank=True, max_length=100, null=True)),
                ('client_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_salute', models.CharField(choices=[(b'MISS', b'Miss.'), (b'MS', b'Ms.'), (b'MRS', b'Mrs.'), (b'MR', b'Mr.')], max_length=5)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('revenue_type', models.CharField(blank=True, choices=[(b'C', b'Cash'), (b'T', b'Trade')], default=b'C', max_length=1, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('agency_comm', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sales_rep_comm', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('grace_period', models.IntegerField(null=True)),
                ('bill_cycle', models.CharField(blank=True, choices=[(b'W', b'Weekly'), (b'B', b'Bi-Weekly'), (b'M', b'Monthly')], max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 1, 20, 54), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 1, 20, 54), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 1, 20, 54), null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.SalesPerson'),
        ),
        migrations.AddField(
            model_name='client',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.Agent'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.ClientGroup'),
        ),
    ]
