# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-06-24 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0012_auto_20200601_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bill_method', models.CharField(blank=True, choices=[(b'FF', b'Flat Fee'), (b'IP', b'Increment By Percentage')], max_length=2, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('base_duration', models.IntegerField(null=True)),
                ('ip_duration1', models.IntegerField(null=True)),
                ('ip_percent1', models.IntegerField(null=True)),
                ('ip_duration2', models.IntegerField(null=True)),
                ('ip_percent2', models.IntegerField(null=True)),
                ('ip_duration3', models.IntegerField(null=True)),
                ('ip_percent3', models.IntegerField(null=True)),
                ('ip_duration4', models.IntegerField(null=True)),
                ('ip_percent4', models.IntegerField(null=True)),
                ('ip_duration5', models.IntegerField(null=True)),
                ('ip_percent6', models.IntegerField(null=True)),
                ('ip_duration7', models.IntegerField(null=True)),
                ('ip_percent7', models.IntegerField(null=True)),
                ('ip_duration8', models.IntegerField(null=True)),
                ('ip_percent8', models.IntegerField(null=True)),
                ('ip_duration9', models.IntegerField(null=True)),
                ('ip_percent9', models.IntegerField(null=True)),
                ('ip_duration10', models.IntegerField(null=True)),
                ('ip_percent10', models.IntegerField(null=True)),
                ('ip_duration11', models.IntegerField(null=True)),
                ('ip_percent11', models.IntegerField(null=True)),
                ('ip_duration12', models.IntegerField(null=True)),
                ('ip_percent12', models.IntegerField(null=True)),
                ('daypart1', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart2', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart3', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart4', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart5', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart6', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart7', models.CharField(blank=True, max_length=96, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 11, 8), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 11, 8), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 11, 8), null=True),
        ),
    ]
