# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-02 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0013_auto_20200624_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeband',
            name='ip_duration6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timeband',
            name='ip_percent5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 2, 18, 22), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 2, 18, 22), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 2, 18, 22), null=True),
        ),
    ]
