# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-02 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0014_auto_20200702_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 2, 18, 27), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 2, 18, 27), null=True),
        ),
        migrations.AlterField(
            model_name='timeband',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 2, 18, 27), null=True),
        ),
    ]
