# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-17 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0015_auto_20200702_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 17, 13, 6), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 17, 13, 6), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 17, 13, 6), null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.SalesPerson'),
        ),
        migrations.AddField(
            model_name='brand',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Client'),
        ),
    ]
