# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-24 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0016_auto_20200717_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spot_duration', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('real_duration', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.Brand')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Client')),
                ('daypart1', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart2', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart3', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart4', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart5', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart6', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart7', models.CharField(blank=True, max_length=96, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpotTypeExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('detail_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpotVoiceOver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('detail_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 14, 39), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 14, 39), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 24, 14, 39), null=True),
        ),
    ]
