# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-08-16 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0017_auto_20200724_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('station_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('max_spot_per_break', models.IntegerField(null=True)),
                ('agency_comm', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('agency_comm_type', models.CharField(blank=True, choices=[(b'F', b'Fixed'), (b'P', b'Percentage')], max_length=1, null=True)),
                ('sales_rep_comm', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sales_rep_comm_type', models.CharField(blank=True, choices=[(b'F', b'Fixed'), (b'P', b'Percentage')], max_length=1, null=True)),
                ('billing_cycle', models.CharField(blank=True, choices=[(b'W', b'Weekly'), (b'B', b'Bi-Weekly'), (b'M', b'Monthly')], max_length=1, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pay_grace_period', models.IntegerField(null=True)),
                ('order_approval_levels', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 16, 11, 42), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 16, 11, 42), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 16, 11, 42), null=True),
        ),
    ]
