# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-02 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0020_auto_20200831_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order_number', models.IntegerField(null=True)),
                ('order_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('revenue_type', models.CharField(blank=True, choices=[(b'C', b'Cash'), (b'T', b'Trade')], max_length=1, null=True)),
                ('billing_type', models.CharField(blank=True, choices=[(b'G', b'Gross'), (b'N', b'Net')], max_length=1, null=True)),
                ('billing_period', models.CharField(blank=True, choices=[(b'W', b'Weekly'), (b'B', b'Bi-Weekly'), (b'M', b'Monthly')], max_length=1, null=True)),
                ('spots_ordered', models.IntegerField(null=True)),
                ('spots_booked', models.IntegerField(null=True)),
                ('Spots_played', models.IntegerField(null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('agency_comm', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('agency_comm_type', models.CharField(blank=True, choices=[(b'F', b'Fixed'), (b'P', b'Percentage')], max_length=1, null=True)),
                ('sales_rep_comm', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('sales_rep_comm_type', models.CharField(blank=True, choices=[(b'F', b'Fixed'), (b'P', b'Percentage')], max_length=1, null=True)),
                ('trade_credit', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('trade_credit_type', models.CharField(blank=True, choices=[(b'F', b'Fixed'), (b'P', b'Percentage')], max_length=1, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('grace_period', models.IntegerField(null=True)),
                ('billing_basis', models.CharField(blank=True, choices=[(b'STD', b'Standard'), (b'DAY', b'Daily'), (b'PRD', b'Billing Period')], max_length=1, null=True)),
                ('approval_count', models.IntegerField(default=0, null=True)),
                ('add_login', models.CharField(blank=True, max_length=15, null=True)),
                ('add_dtime', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 14, 45), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderApprovals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(null=True)),
                ('add_dtime', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 14, 45), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderApprover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('user_title', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spot_count', models.IntegerField(null=True)),
                ('mention_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 14, 45), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 14, 45), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 14, 45), null=True),
        ),
        migrations.AddField(
            model_name='orderapprovals',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.OrderApprover'),
        ),
        migrations.AddField(
            model_name='orderapprovals',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='account_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.SalesPerson'),
        ),
        migrations.AddField(
            model_name='order',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.Agent'),
        ),
        migrations.AddField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.Brand'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Client'),
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.OrderPackage'),
        ),
    ]
