# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-04 17:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0026_auto_20200904_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='billing_basis',
            field=models.CharField(blank=True, choices=[(b'STD', b'Standard'), (b'DAY', b'Daily'), (b'PRD', b'Billing Period')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 4, 17, 20), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 4, 17, 20), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 4, 17, 20), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 4, 17, 20), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 4, 17, 20), null=True),
        ),
    ]
