# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-04 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0027_auto_20200904_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 4, 18, 35), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 4, 18, 35), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_basis',
            field=models.CharField(blank=True, choices=[(b'STD', b'Standard'), (b'DAY', b'Daily'), (b'PRD', b'Billing Period')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 4, 18, 35), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 4, 18, 35), null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='billing_basis',
            field=models.CharField(blank=True, choices=[(b'STD', b'Standard'), (b'DAY', b'Daily'), (b'PRD', b'Billing Period')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 4, 18, 35), null=True),
        ),
    ]
