# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-11 20:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0030_auto_20200906_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('week_days', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='BreakLayoutLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField()),
                ('break_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('max_spots', models.IntegerField()),
                ('break_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.BreakLayout')),
            ],
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 20, 30), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 20, 30), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 20, 30), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 20, 30), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 20, 30), null=True),
        ),
    ]
