# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-12 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0032_auto_20200911_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaklayout',
            name='time_interval',
            field=models.IntegerField(choices=[(15, b'15 Mins'), (10, b'10 Mins'), (5, b'5 Mins'), (1, b'1 Min')], default=15),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 12, 11, 27), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 12, 11, 27), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 12, 11, 27), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 12, 11, 27), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 12, 11, 27), null=True),
        ),
    ]
