# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-13 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0033_auto_20200912_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='break_duration',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='setup',
            name='break_max_spots',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='setup',
            name='break_time_interval',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 13, 12, 32), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 13, 12, 32), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 13, 12, 32), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 13, 12, 32), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 13, 12, 32), null=True),
        ),
    ]
