# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-14 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0035_auto_20200913_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaklayoutline',
            name='break_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 14, 11, 6), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 14, 11, 6), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 14, 11, 6), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 14, 11, 6), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 14, 11, 6), null=True),
        ),
    ]
