# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-16 20:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0036_auto_20200914_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('artist_type', models.CharField(choices=[(b'F', b'FEMALE'), (b'M', b'MALE'), (b'G', b'GROUP')], max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('scheule_time', models.TimeField()),
                ('schedule_hour', models.IntegerField(default=0)),
                ('fade_in', models.IntegerField(default=0)),
                ('fade_out', models.IntegerField(default=0)),
                ('fade_delay', models.IntegerField(default=0)),
                ('play_status', models.CharField(blank=True, choices=[(b'CUED', b'CUED'), (b'PLAYED', b'PLAYED'), (b'CANCELLED', b'CANCELLED')], max_length=15, null=True)),
                ('play_date', models.DateField(null=True)),
                ('play_time', models.TimeField(null=True)),
                ('auto_transition', models.IntegerField(default=0)),
                ('live_transition', models.IntegerField(default=0)),
                ('track_type', models.CharField(choices=[(b'SONG', b'SONG'), (b'COMM', b'COMMERCIAL')], default=b'SONG', max_length=8)),
                ('break_duration', models.IntegerField(default=0)),
                ('break_start_win', models.IntegerField(default=0)),
                ('break_end_win', models.IntegerField(default=0)),
                ('break_max_spots', models.IntegerField(default=0)),
                ('booked_spots', models.IntegerField(default=0)),
                ('break_duration_left', models.IntegerField(default=0)),
                ('break_mode', models.CharField(choices=[(b'SINGLE', b'SINGLE'), (b'JOINT', b'JOINT')], default=b'SINGLE', max_length=8)),
                ('break_status', models.CharField(choices=[(b'FIXED', b'FIXED'), (b'OPEN', b'OPEN')], default=b'OPEN', max_length=6)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daypart1', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart2', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart3', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart4', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart5', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart6', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart7', models.CharField(blank=True, max_length=96, null=True)),
                ('title', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 20, 58), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 20, 58), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 20, 58), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 20, 58), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 20, 58), null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Track'),
        ),
    ]
