# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-16 21:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0037_auto_20200916_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='track',
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 21, 1), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 21, 1), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 21, 1), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 21, 1), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 21, 1), null=True),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
