# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-16 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0038_auto_20200916_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Artist')),
                ('daypart1', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart2', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart3', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart4', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart5', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart6', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart7', models.CharField(blank=True, max_length=96, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 21, 2), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 21, 2), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 21, 2), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 21, 2), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 21, 2), null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='track',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rave.Track'),
            preserve_default=False,
        ),
    ]
