# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-21 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0043_auto_20200918_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 21, 18, 55), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 21, 18, 55), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 21, 18, 55), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 21, 18, 55), null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='auto_transition',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='booked_spots',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_duration',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_duration_left',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_end_win',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_max_spots',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_mode',
            field=models.CharField(blank=True, choices=[(b'SINGLE', b'SINGLE'), (b'JOINT', b'JOINT')], default=b'SINGLE', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_start_win',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_status',
            field=models.CharField(blank=True, choices=[(b'FIXED', b'FIXED'), (b'OPEN', b'OPEN')], default=b'OPEN', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fade_delay',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fade_in',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fade_out',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='live_transition',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_hour',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 21, 18, 55), null=True),
        ),
    ]
