# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-10-07 15:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0044_auto_20200921_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('booking_count', models.IntegerField(default=0, null=True)),
                ('segment_value', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('add_login', models.CharField(blank=True, max_length=15, null=True)),
                ('add_dtime', models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 7, 15, 54), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(blank=True, choices=[(b'READY', b'READY'), (b'PLAYED', b'PLAYED'), (b'CANCEL', b'CANCEL')], default=b'READY', max_length=8, null=True)),
                ('play_date', models.DateField(null=True)),
                ('play_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 7, 15, 54), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.IntegerField(default=0, null=True)),
                ('weight', models.IntegerField(default=100, null=True)),
                ('seq_no', models.IntegerField(default=1, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Spot')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Track')),
            ],
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 7, 15, 54), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 7, 15, 54), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 7, 15, 54), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 7, 15, 54), null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_mode',
            field=models.CharField(blank=True, choices=[(b'SINGLE', b'SINGLE'), (b'MIXED', b'MIXED')], default=b'MIXED', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_status',
            field=models.CharField(blank=True, choices=[(b'LOCKED', b'LOCKED'), (b'OPEN', b'OPEN')], default=b'OPEN', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 7, 15, 54), null=True),
        ),
        migrations.AddField(
            model_name='orderbooking',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.SpotAudio'),
        ),
        migrations.AddField(
            model_name='orderbooking',
            name='booking_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.BookingSegment'),
        ),
        migrations.AddField(
            model_name='orderbooking',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Schedule'),
        ),
        migrations.AddField(
            model_name='bookingsegment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Order'),
        ),
        migrations.AddField(
            model_name='bookingsegment',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Spot'),
        ),
    ]
