# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-10-21 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0045_auto_20201007_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsegment',
            name='spot',
        ),
        migrations.AddField(
            model_name='orderbooking',
            name='spot',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='rave.Spot'),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 18, 51), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 18, 51), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 18, 51), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 18, 51), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 18, 51), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 18, 51), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 18, 51), null=True),
        ),
    ]
