# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-11-03 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0052_auto_20201029_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 3, 22, 5), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 3, 22, 5), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 3, 22, 5), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 3, 22, 5), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 3, 22, 5), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 3, 22, 5), null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='real_duration',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='spot_duration',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 3, 22, 5), null=True),
        ),
    ]
