# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-12-19 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0053_auto_20201103_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_type',
            field=models.CharField(choices=[(b'SONG', b'Song'), (b'COMM', b'Commercial'), (b'JING', b'Jingle'), (b'DROP', b'Drop'), (b'NBITE', b'News Bite')], default=b'SONG', max_length=6),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 19, 13, 6), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 19, 13, 6), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 19, 13, 6), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 19, 13, 6), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.SpotAudio'),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 19, 13, 6), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 19, 13, 6), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 19, 13, 6), null=True),
        ),
    ]
