# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-01-03 10:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0054_auto_20201219_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 3, 10, 48), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 3, 10, 48), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 3, 10, 48), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 3, 10, 48), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='booking_status',
            field=models.CharField(blank=True, choices=[(b'READY', b'READY'), (b'PLAYED', b'PLAYED'), (b'CANCEL', b'CANCEL')], default=b'READY', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 3, 10, 48), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 3, 10, 48), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 3, 10, 48), null=True),
        ),
    ]
