# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-01-03 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0056_auto_20210103_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbooking',
            name='booking_status',
            field=models.CharField(blank=True, choices=[(b'READY', b'READY'), (b'PLAYED', b'PLAYED'), (b'CANCELLED', b'CANCEL')], default=b'READY', max_length=15, null=True),
        ),
    ]
