# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-04-04 10:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0059_auto_20210329_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daypart1', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart2', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart3', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart4', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart5', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart6', models.CharField(blank=True, max_length=96, null=True)),
                ('daypart7', models.CharField(blank=True, max_length=96, null=True)),
                ('title', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=255)),
                ('track_type', models.CharField(choices=[(b'SONG', b'Song'), (b'COMM', b'Commercial'), (b'JING', b'Jingle'), (b'DROP', b'Drop'), (b'NBITE', b'News Bite')], default=b'SONG', max_length=6)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('start_marker', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('fade_in_marker', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('intro_marker', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('extro_marker', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('fade_out_marker', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('end_marker', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('add_dtime', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 4, 10, 34), null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('play_count', models.IntegerField(null=True)),
                ('audio_year', models.IntegerField(null=True)),
                ('audio_month', models.IntegerField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.Artist')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.Folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=100)),
                ('intensity', models.CharField(choices=[(b'low', b'LOW'), (b'vlow', b'VERY LOW'), (b'medium', b'MEDIUM'), (b'high', b'HIGH'), (b'vhigh', b'VERY HIGH')], max_length=8)),
                ('timbre', models.CharField(choices=[(b'low', b'LOW'), (b'vlow', b'VERY LOW'), (b'medium', b'MEDIUM'), (b'high', b'HIGH'), (b'vhigh', b'VERY HIGH')], max_length=8)),
                ('pitch', models.CharField(choices=[(b'low', b'LOW'), (b'vlow', b'VERY LOW'), (b'medium', b'MEDIUM'), (b'high', b'HIGH'), (b'vhigh', b'VERY HIGH')], max_length=8)),
                ('rhythm', models.CharField(choices=[(b'low', b'LOW'), (b'vlow', b'VERY LOW'), (b'medium', b'MEDIUM'), (b'high', b'HIGH'), (b'vhigh', b'VERY HIGH')], max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='folder',
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 4, 10, 34), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 4, 10, 34), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 4, 10, 34), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 4, 10, 34), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 4, 10, 34), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 4, 10, 34), null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.Audio'),
        ),
        migrations.AlterField(
            model_name='spotaudio',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rave.Audio'),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 4, 10, 34), null=True),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AddField(
            model_name='audio',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.Genre'),
        ),
        migrations.AddField(
            model_name='audio',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rave.Mood'),
        ),
    ]
