# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-08-19 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0065_auto_20210424_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 19, 19, 40), null=True),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 19, 19, 40), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 19, 19, 40), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 19, 19, 40), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 19, 19, 40), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 19, 19, 40), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 19, 19, 40), null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_item_type',
            field=models.CharField(choices=[(b'SONG', b'SONG'), (b'COMM-BREAK', b'COMMERCIAL')], default=b'SONG', max_length=20),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 19, 19, 40), null=True),
        ),
    ]
