# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-12-06 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0067_auto_20210819_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbooking',
            name='book_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderbooking',
            name='book_hour',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderbooking',
            name='book_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 6, 17, 0), null=True),
        ),
    ]
