# Generated by Django 4.0.5 on 2022-06-28 10:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0068_auto_20211206_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_type',
            field=models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE'), ('G', 'GROUP')], max_length=1),
        ),
        migrations.AlterField(
            model_name='audio',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 10, 47), null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.artist'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_type',
            field=models.CharField(choices=[('SONG', 'Song'), ('COMM', 'Commercial'), ('JING', 'Jingle'), ('DROP', 'Drop'), ('NBITE', 'News Bite')], default='SONG', max_length=20),
        ),
        migrations.AlterField(
            model_name='audio',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.folder'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.genre'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.mood'),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 10, 47), null=True),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='order',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.order'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.salesperson'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.client'),
        ),
        migrations.AlterField(
            model_name='breaklayout',
            name='time_interval',
            field=models.IntegerField(choices=[(15, '15 Mins'), (10, '10 Mins'), (5, '5 Mins'), (1, '1 Min')], default=15),
        ),
        migrations.AlterField(
            model_name='breaklayoutline',
            name='break_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.breaklayout'),
        ),
        migrations.AlterField(
            model_name='client',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.salesperson'),
        ),
        migrations.AlterField(
            model_name='client',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.agent'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bill_cycle',
            field=models.CharField(blank=True, choices=[('W', 'Weekly'), ('B', 'Bi-Weekly'), ('M', 'Monthly')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.clientgroup'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_salute',
            field=models.CharField(choices=[('MISS', 'Miss.'), ('MS', 'Ms.'), ('MRS', 'Mrs.'), ('MR', 'Mr.')], max_length=5),
        ),
        migrations.AlterField(
            model_name='client',
            name='revenue_type',
            field=models.CharField(blank=True, choices=[('C', 'Cash'), ('T', 'Trade')], default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 10, 47), null=True),
        ),
        migrations.AlterField(
            model_name='contentauth',
            name='access_bit',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AlterField(
            model_name='mood',
            name='intensity',
            field=models.CharField(choices=[('low', 'LOW'), ('vlow', 'VERY LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH'), ('vhigh', 'VERY HIGH')], max_length=8),
        ),
        migrations.AlterField(
            model_name='mood',
            name='pitch',
            field=models.CharField(choices=[('low', 'LOW'), ('vlow', 'VERY LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH'), ('vhigh', 'VERY HIGH')], max_length=8),
        ),
        migrations.AlterField(
            model_name='mood',
            name='rhythm',
            field=models.CharField(choices=[('low', 'LOW'), ('vlow', 'VERY LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH'), ('vhigh', 'VERY HIGH')], max_length=8),
        ),
        migrations.AlterField(
            model_name='mood',
            name='timbre',
            field=models.CharField(choices=[('low', 'LOW'), ('vlow', 'VERY LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH'), ('vhigh', 'VERY HIGH')], max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='account_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.salesperson'),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 10, 47), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.agent'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agency_comm_type',
            field=models.CharField(blank=True, choices=[('F', 'Fixed'), ('P', 'Percentage')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_basis',
            field=models.CharField(blank=True, choices=[('STD', 'Standard'), ('DAY', 'Daily'), ('PRD', 'Billing Period')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_period',
            field=models.CharField(blank=True, choices=[('W', 'Weekly'), ('B', 'Bi-Weekly'), ('M', 'Monthly')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('G', 'Gross'), ('N', 'Net')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.brand'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.orderpackage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='revenue_type',
            field=models.CharField(blank=True, choices=[('C', 'Cash'), ('T', 'Trade')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sales_rep_comm_type',
            field=models.CharField(blank=True, choices=[('F', 'Fixed'), ('P', 'Percentage')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_credit_type',
            field=models.CharField(blank=True, choices=[('F', 'Fixed'), ('P', 'Percentage')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 10, 47), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.orderapprover'),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.order'),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.spotaudio'),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('READY', 'READY'), ('PLAYED', 'PLAYED'), ('CANCELLED', 'CANCEL')], default='READY', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='bookingsegment',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.bookingsegment'),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 10, 47), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.schedule'),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='spot',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.spot'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 10, 47), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.gender'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.audio'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_mode',
            field=models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('MIXED', 'MIXED')], default='MIXED', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_status',
            field=models.CharField(blank=True, choices=[('LOCKED', 'LOCKED'), ('OPEN', 'OPEN')], default='OPEN', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='play_status',
            field=models.CharField(blank=True, choices=[('WAITING', 'WAITING'), ('CUED', 'CUED'), ('PLAYED', 'PLAYED'), ('CANCELLED', 'CANCELLED')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_item_type',
            field=models.CharField(choices=[('SONG', 'SONG'), ('COMM-BREAK', 'COMMERCIAL'), ('COMM-AUDIO', 'COMMERCIAL-AUDIO'), ('JINGLE', 'JINGLE')], default='SONG', max_length=20),
        ),
        migrations.AlterField(
            model_name='setup',
            name='agency_comm_type',
            field=models.CharField(blank=True, choices=[('F', 'Fixed'), ('P', 'Percentage')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='billing_basis',
            field=models.CharField(blank=True, choices=[('STD', 'Standard'), ('DAY', 'Daily'), ('PRD', 'Billing Period')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('W', 'Weekly'), ('B', 'Bi-Weekly'), ('M', 'Monthly')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('G', 'Gross'), ('N', 'Net')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='revenue_type',
            field=models.CharField(blank=True, choices=[('C', 'Cash'), ('T', 'Trade')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='sales_rep_comm_type',
            field=models.CharField(blank=True, choices=[('F', 'Fixed'), ('P', 'Percentage')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.brand'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.client'),
        ),
        migrations.AlterField(
            model_name='spotaudio',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.audio'),
        ),
        migrations.AlterField(
            model_name='spotaudio',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rave.spot'),
        ),
        migrations.AlterField(
            model_name='timeband',
            name='bill_method',
            field=models.CharField(blank=True, choices=[('FF', 'Flat Fee'), ('IP', 'Increment By Percentage')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 28, 10, 47), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.gender'),
        ),
    ]
