# Generated by Django 4.0.5 on 2023-03-27 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0072_audio_file_extension_alter_audio_add_dtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='fade_delay_marker',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 27, 20, 40), null=True),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 27, 20, 40), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 27, 20, 40), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 27, 20, 40), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 27, 20, 40), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 27, 20, 40), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 27, 20, 40), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 27, 20, 40), null=True),
        ),
    ]
