# Generated by Django 4.0.5 on 2023-08-18 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0075_orderbooking_book_seq_alter_audio_add_dtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaklayout',
            name='break_fill_method',
            field=models.CharField(blank=True, choices=[('S', 'Sequential'), ('R', 'Random')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='breaklayoutline',
            name='break_fill_method',
            field=models.CharField(blank=True, choices=[('S', 'Sequential'), ('R', 'Random')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 18, 20, 4), null=True),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 18, 20, 4), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 18, 20, 4), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 18, 20, 4), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 18, 20, 4), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 18, 20, 4), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 18, 20, 4), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 18, 20, 4), null=True),
        ),
    ]
