# Generated by Django 4.0.5 on 2023-08-21 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0076_breaklayout_break_fill_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='break_fill_method',
            field=models.CharField(blank=True, choices=[('S', 'Sequential'), ('R', 'Random')], default='S', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 21, 12, 11), null=True),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 21, 12, 11), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 21, 12, 11), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 21, 12, 11), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 21, 12, 11), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 21, 12, 11), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 21, 12, 11), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 21, 12, 11), null=True),
        ),
    ]
