# Generated by Django 4.0.5 on 2024-05-28 20:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0079_rename_audio_orderbooking_booked_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 28, 20, 40), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 28, 20, 40), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 28, 20, 40), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 28, 20, 40), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='booked_audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rave.audio'),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 28, 20, 40), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 28, 20, 40), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 28, 20, 40), null=True),
        ),
    ]
