# Generated by Django 5.2.3 on 2026-02-24 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rave', '0085_reasonvoidbooking_orderbooking_add_dtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='cts_filepath',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsegment',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 24, 11, 21), null=True),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 24, 11, 21), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 24, 11, 21), null=True),
        ),
        migrations.AlterField(
            model_name='orderapprovals',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 24, 11, 21), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 24, 11, 21), null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='play_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 24, 11, 21), null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 24, 11, 21), null=True),
        ),
        migrations.AlterField(
            model_name='voiceover',
            name='add_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 2, 24, 11, 21), null=True),
        ),
    ]
